---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8010  
eureka:
  instance:
    hostname: eurekahost 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 
      
---
# This is primary profile 
spring:
  profiles: primary
  application:
    name: eureka-server-clustered
server:
  port: 8011 
eureka:
  instance:
    hostname: eureka-primary 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      
---
# This is secondary profile 
spring:
  profiles: secondary
  application:
    name: eureka-server-clustered
server:
  port: 8012 
eureka:
  instance:
    hostname: eureka-secondary 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-tertiary:8013/eureka/
      
---
# This is tertiary profile 
spring:
  profiles: tertiary
  application:
    name: eureka-server-clustered
server:
  port: 8013 
eureka:
  instance:
    hostname: eureka-tertiary 
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/               